FROM openjdk:8

EXPOSE 9083

ADD target/pension-disbursement-microservice-0.0.1-SNAPSHOT.jar pension-disbursement-microservice-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "pension-disbursement-microservice-0.0.1-SNAPSHOT.jar"]