FROM openjdk:8

EXPOSE 9085

ADD target/Pension-Management-portal-0.0.1-SNAPSHOT.jar Pension-Management-portal-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "Pension-Management-portal-0.0.1-SNAPSHOT.jar"]