FROM openjdk:8

EXPOSE 9081

ADD target/pensioner-detail-microservice-0.0.1-SNAPSHOT.jar pensioner-detail-microservice-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "pensioner-detail-microservice-0.0.1-SNAPSHOT.jar"]