FROM openjdk:8

EXPOSE 9084

ADD target/process-pension-microservice-0.0.1-SNAPSHOT.jar process-pension-microservice-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "process-pension-microservice-0.0.1-SNAPSHOT.jar"]